version: "3"

services:
  nginx:
    image: nginx:1-alpine
    env_file: .env
    depends_on:
      - php
    ports:
      - 8888:80
    volumes:
      - ./project:/var/www/app:rw
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    tty: true

  php:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes:
      - ./project:/var/www/app:rw
    tty: true

  mysql:
      image: mysql:5.6
      environment:
          MYSQL_ROOT_PASSWORD: symf0ny
      ports:
          - "3333:3306"