<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\GroupController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/GroupController.php';

return $this->services['App\Controller\GroupController'] = new \App\Controller\GroupController(($this->services['App\Repository\GroupRepository'] ?? $this->load('getGroupRepositoryService.php')), ($this->services['App\Repository\UsersGroupRepository'] ?? $this->load('getUsersGroupRepositoryService.php')));
