<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC99xfZ6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC99xfZ6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC99xfZ6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC99xfZ6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerC99xfZ6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'C99xfZ6',
    'container.build_id' => 'dcae2c28',
    'container.build_time' => 1555782018,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC99xfZ6');
