<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKnYxh3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKnYxh3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHKnYxh3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHKnYxh3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHKnYxh3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HKnYxh3',
    'container.build_id' => '9c235201',
    'container.build_time' => 1555697015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKnYxh3');
